### ISSUE TITLE
[3.2.0] ACS Attack

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#399]
An error in the picture occurs in the ACS attack task.

<img width="1915" alt="ACS Attack" src="https://user-images.githubusercontent.com/16218107/97094223-a3bf7280-165b-11eb-94e6-b1b3eae3b53f.png">

**Comment by LucasKovacs** [comment]
@BeReal86 this is a 3.2 error only

**Comment by duhow** [comment]
Seems to be introduced in 693d900cb .

**Comment by LucasKovacs** [comment]
@BeReal86 this is fixed and ready for quality

**Comment by BeReal86** [comment]
> @BeReal86 this is a 3.2 error only

@LucasKovacs  
You forgot it, it became a habit, I wrote all 3.1 version.  whereas it would be version 3.2.  You are right.

**Comment by BeReal86** [comment]
A strange problem occurred in the ACS system as in the video. The fleet can be viewed on its page without inviting the player to ACS.

https://drive.google.com/file/d/1HAtaQTkGoWnYG4vDEl9JrnJTD8PXj8n4/view?usp=sharing

**Comment by LucasKovacs** [comment]
**Evidence** - @BeReal86 pay attention to every details before reporting anything

**Attacker 1 - Two missions are sent. One to 1:1:6 (ACS) and one to 1:1:7 (normal)**
<img width="561" alt="Screenshot 2020-11-12 at 19 47 23" src="https://user-images.githubusercontent.com/3051274/98982953-69d9e180-2520-11eb-8d2b-505dfd94ffbb.png">

**Attacker 2 - One mission is sent. One to 1:1:6 (ACS) with attacker 1**
<img width="562" alt="Screenshot 2020-11-12 at 19 47 29" src="https://user-images.githubusercontent.com/3051274/98983005-7d854800-2520-11eb-86ce-bb678f6a4a17.png">

**Enemy 1 - Is receiving two attacks on ACS mode, one from 1:1:1 and another from 1:28:15*
<img width="564" alt="Screenshot 2020-11-12 at 19 47 34" src="https://user-images.githubusercontent.com/3051274/98983072-97bf2600-2520-11eb-83c7-27aefa880e7a.png">

**Enemy 2 - Is receiving one normal attack from 1:1:1*
<img width="558" alt="Screenshot 2020-11-12 at 19 48 26" src="https://user-images.githubusercontent.com/3051274/98983126-a60d4200-2520-11eb-8587-1f718f885352.png">

**Enemy 3 - no attacks are visible, no acs are visible - nothing nada!*
<img width="567" alt="Screenshot 2020-11-12 at 19 48 38" src="https://user-images.githubusercontent.com/3051274/98983231-c63d0100-2520-11eb-84be-7f324feaac96.png">

**Comment by BeReal86** [comment]
What I want to point out there is that I did attack the player at the A coordinate. Fleet action appears on the screen of the other player (i.e. the player I will invite to ACS screen) without sending an ACS invitation, without inviting ACS I will try this again.

**Comment by BeReal86** [comment]
Work fine

**Comment by LucasKovacs** [comment]
This issue was a good catch! too bad it was not checked before 3.1

**Comment by BeReal86** [comment]
it hadn't really caught my attention. But sometimes different ideas come to my mind while checking other things. I'll be more careful.
